name: Run Selenium SIDE File

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: "0 6 * * *" # Runs daily at 6:00 AM (adjust as needed)

jobs:
  run-side:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Selenium SIDE Runner
      run: npm install -g selenium-side-runner

    - name: Run SIDE File
      run: selenium-side-runner automation/your-file.side
