name: Run Selenium SIDE File

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  run-side:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Selenium SIDE Runner
      run: npm install -g selenium-side-runner

    - name: Run SIDE File in Loop
      run: |
        for i in {1..6}; do
          selenium-side-runner "tests/feza smart.side"
          sleep 10
        done
